### PR TITLE
Who can live without nano?

### PR DESCRIPTION
**Pull request by loctauxphilippe**

### CODE REVIEW

**Comment by Foggalong** [comment]
Is vim not enough for you? :P

**Comment by thorsummoner** [comment]
Hah, in all playfulness, nano is the worst CLI text editor. Imo~ still good, just way less.. Handy

**Comment by Foggalong** [comment]
Do you even `ed`

**Comment by mpnordland** [comment]
I can make do with vi, but I'd rather not live without vim.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Foggalong** [comment]
Well that's good because it is vim :P

**Comment by loctauxphilippe** [comment]
@Foggalong Vim is too complicated, and nano is much user-friendly imo

**Comment by Foggalong** [comment]
If you're at the technical level where you're wanting to use a terminal text editor it's worth into learn the basics of vim. My guess is that we're not shipping nano with the logic that if they want user friendly they should use gedit.

**Comment by loctauxphilippe** [comment]
@Foggalong Yes you're right dudie. I'll close it. Thanks for help

**Comment by mpnordland** [comment]
I must protest that "user-friendly" is not a constant value. It depends
on the concept of a user, which is defined by the audience you target.
While certain factors may improve the UX universally, such as
consistency and discoverability, in the end the difference between user
types by far outweighs them.
-- 
Micah Nordland <micah@rehack.com>
My public key: http://www.thoughtfuldragon.com/public.key

**Comment by Foggalong** [comment]
Well we targeting gamers, so we'll just have them use Steam to edit text files.

**Comment by loctauxphilippe** [comment]
@Foggalong Can I get a tutorial on how to do that? Open text files with Steam should be awesome! :P

**Comment by Foggalong** [comment]
Just a joke at how Steam is slowly becoming the swiss army knife of software. Games, chat client, general software center, music player, etc

**Comment by loctauxphilippe** [comment]
@Foggalong Really? I didn't know

**Comment by thorsummoner** [comment]
So Nano is not going to be included in Ozon os? I mean sure, anyone can install it themselves but It is nice to have options preconfiguered. Not like I've ever seen a linux version consume an entire DVD before anyway (not like people even still use dvd's as installation media)

**Comment by Foggalong** [comment]
We do already ship vim, gedit, and ed. If we shipped every piece of software people wanted we'd have to send Ozon out on physical harddrives :P

**Pull request closed without merging**
